### ISSUE TITLE
black screen after rebooting

### ISSUE THREAD

**Issue by gjm19761** [ChrisTitusTech/ArchTitus#391]
my screen is blank but theres activity on the pc.

seems not working after script does update and upgrade.

im using a nvidia 3080 all was fine before script updated os

**Comment by gjm19761** [comment]
any ideas???

**Comment by t-persson** [comment]
I am able to reproduce this, but I have not yet tried to solve it. What I have seen with nvidia and hyprland is that you need to set `nvidia_drm.modeset=1` ( I also set `nvidia_drm.fbdev=1` ), but it didnt instantly help when installing using this repository.
Next is to test setting the parameters `nvidia nvidia_modeset nvidia_uvm nvidia_drm` in initramfs

I dont have time to look i to that myself yet, but I recommend trying 

Sources:
* https://wiki.hyprland.org/Nvidia/
* https://wiki.archlinux.org/title/NVIDIA#DRM_kernel_mode_setting

**Comment by gjm19761** [comment]
i think its something to do with the newer kernels not supporting nvidia and when the script updated the system it installed the new kernel :( i have no idea on how to fix this, maybe titus script could update then install a usable kernel for us

**Comment by t-persson** [comment]
I fixed my problem by changing from lightdm to sddm

**Comment by gjm19761** [comment]
but how, have no display at all??

**Comment by t-persson** [comment]
> but how, have no display at all??
>  

Ctrl+Alt+F3 worked for me to get a tty, then i just installed sddm, disabled lightdm with systemd and enabled sddm with systemd

**Comment by gjm19761** [comment]
still not working? think issue with new kernel and broken nvidia?
